Use defined image version for pwpush-postgres
The dockerhub repo doesnt have a  "latest" version. So, to run a docker-compose, use defined version 1.0 .

ERROR MESSAGE:
 "Pulling passwordpusher (pglombardo/pwpush-postgres:latest)...
ERROR: manifest for pglombardo/pwpush-postgres:latest not found"